language: php
sudo: true
dist: trusty

php:

- 7.2
- nightly

before_install:
- sudo apt-get update
- sudo apt-get install make build-essential automake
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- git checkout 1.0.13
- ./autogen.sh
- ./configure && make check
- sudo make install
- cd ..
- pecl install libsodium
- echo "extension = sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:

- composer install
- composer self-update
- composer update
- chmod +x ./test/phpunit.sh

script: ./test/phpunit.sh
