language: php
sudo: true
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: "7.2"
    - php: "master"
    - php: "nightly"
  allow_failures:
    - php: "master"
    - php: "nightly"

install:

- composer self-update
- composer update

script:
- vendor/bin/phpunit
- vendor/bin/psalm
